#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f sigdelay.vcd

# # view if USB is connected
sudo lsusb
sudo dmesg | grep tty

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace sigdelay.sv --exe sigdelay_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vsigdelay.mk Vsigdelay

# run executable simulation file
obj_dir/Vsigdelay